### ISSUE TITLE
Install Istio for kyma 2.6.0 failed

### ISSUE THREAD

**Issue by johgoe** [kyma-project/cli#1361] opened 2022-08-29 09:46 UTC
**Description**

When upgrade kyma 2.5.1 to 2.6.0 an error occurs which exists the cli

**Expected result**

**Actual result**

```
2022/08/29 11:42:55 worker with func exits from a panic: assignment to entry in nil map
X Component 'istio' failed. Retrying...
context canceled

2022/08/29 11:42:55 worker with func exits from panic: goroutine 617 [running]:
github.com/panjf2000/ants/v2.(*goWorkerWithFunc).run.func1.1()
        /home/prow/go/pkg/mod/github.com/panjf2000/ants/v2@v2.4.8/worker_func.go:58 +0x10c
panic({0x27e7f20, 0x3087200})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/data.getAllPodsWithNamespaceAnnotations.func2()
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/reset/data/gatherer.go:186 +0x372
github.com/avast/retry-go.Do(0xc000d766f8, {0xc001b03908, 0x3, 0xc000a34e90?})
        /home/prow/go/pkg/mod/github.com/avast/retry-go@v3.0.0+incompatible/retry.go:127 +0x1e6
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/data.getAllPodsWithNamespaceAnnotations({0x30cc070, 0xc000a10600}, {0xc001b03908, 0x3, 0x3})
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/reset/data/gatherer.go:167 +0x15b
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/data.(*DefaultGatherer).GetPodsWithoutSidecar(0x0?, {0x30cc070?, 0xc000a10600?}, {0xc001b03908?, 0x30b38e0?, 0xc0002481e0?}, 0x70?)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/reset/data/gatherer.go:87 +0xaa
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/proxy.(*DefaultIstioProxyReset).Run(0xc0003478a0, {{0x30b38e0, 0xc0002481e0}, 0x1, {0xc01f9d0060, 0x25}, {0xc000efded8, 0x11}, 0x5, 0x12a05f200, ...})
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/reset/proxy/proxy.go:76 +0x6d2
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/actions.(*DefaultIstioPerformer).ResetProxy(0xc00d77ef60, {0x30b38e0, 0xc0002481e0}, {0xc000c6c600?, 0xc00d77ef60?}, {0x30a2838, 0xc000d92630}, {0x7ffda89d3c12, 0x5}, {0xc008af53b4, ...}, ...)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/actions/performer.go:372 +0x1f5
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio.(*ProxyResetPostAction).Run(0xc00011c890, 0xc0000af540)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/action.go:158 +0x2f4
github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/actions.(*ActionAggregate).Run(0xc000b9e048, 0xc0000af540?)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/instances/istio/actions/aggregate_action.go:21 +0x77
github.com/kyma-incubator/reconciler/pkg/reconciler/service.(*runner).reconcile(0xc001124048, {0x30b38e0?, 0xc0002481e0}, {0x30c3418?, 0xc0002485a0}, 0xc0006a0000)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/service/runner.go:207 +0x54e
github.com/kyma-incubator/reconciler/pkg/reconciler/service.(*runner).Run.func1()
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/service/runner.go:92 +0x1ce
github.com/avast/retry-go.Do(0xc000d77720, {0xc001afb6f8, 0x5, 0xc001122090?})
        /home/prow/go/pkg/mod/github.com/avast/retry-go@v3.0.0+incompatible/retry.go:127 +0x1e6
github.com/kyma-incubator/reconciler/pkg/reconciler/service.(*runner).Run(0xc001124048, {0x30b38e0, 0xc0002481e0}, 0xc0006a0000, {0x308b080?, 0xc001122090?}, 0x0?)
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/service/runner.go:106 +0x6f3
github.com/kyma-incubator/reconciler/pkg/reconciler/service.(*ComponentReconciler).newRunnerFunc.func1()
        /home/prow/go/pkg/mod/github.com/kyma-incubator/reconciler@v0.0.0-20220823084016-5bfafa4d7bc5/pkg/reconciler/service/reconciler.go:282 +0x15b
github.com/kyma-incubator/reconciler/pkg/reconciler/service.(*ComponentReconciler).StartLocal(0xc000a
```

**Steps to reproduce**

**Troubleshooting**

**Comment by johgoe** [comment] 2022-08-29 09:56
I think the issue is not in CLI but in Reconciler. See https://github.com/kyma-incubator/reconciler/issues/1169

**Comment by strekm** [comment] 2022-08-30 05:05
closing this one as a duplicate of https://github.com/kyma-incubator/reconciler/issues/1169

**Closed by strekm** 2022-08-30 05:05 UTC

**Comment by johgoe** [comment] 2022-08-30 10:21
As it is fixed in reconciler now, only the version bump and a new cli release is required to fix the current installer for Pods without any annotations.
