### ISSUE TITLE
Kyma installation fails when development-artifacts job if not finished

### ISSUE THREAD

**Issue by kjaksik** [kyma-project/cli#398] opened 2020-03-04 14:43 UTC
**Description**

When installing Kyma from the master there is a case when it doesn't install. It happens when the `post-master-developer-artifacts` job has not yet finished. Installer cannot pull the new image since it's not build yet and the installation is stuck on the `Installation files loaded` step. CLI checks the latest commit ID but it doesn't check if the artifacts can be found on the bucket.
It happens very often during `compass-integration` jobs and retesting them is very time consuming.

**Expected result**

Installed Kyma

**Actual result**

Installation stuck on `Installation files loaded`

**Steps to reproduce**

`kyma install --source latest` when `post-master-development-artifacts` job is still running

**Comment by kjaksik** [comment] 2020-03-04 14:47
Example job that failed because of this can be found [here](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-compass-integration/1235128729412308992)

**Comment by a-thaler** [comment] 2020-03-04 15:08
You would expect that CLI searches for the last successful master? Or a well defined failure message

**Comment by aszecowka** [comment] 2020-03-04 15:47
@a-thaler:
I would expect (but I am not @kjaksik ) that CLI searches for the last successful master. 
If we choose the option with failing we can have many failed jobs on Prow. Publishing artifacts sometimes took 10 minutes, but sometimes one hour, so it means that for one hour we are not able to start our pipelines, because it will immediatelly fail.

**Comment by a-thaler** [comment] 2020-03-04 15:51
I will close it as duplicate of https://github.com/kyma-project/cli/issues/206

**Closed by a-thaler** 2020-03-04 15:51 UTC
Labels: area/cli, bug
