### ISSUE TITLE
Kyma CLI should possible consume manifest,  defaultCR from URL

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1756] opened 2023-08-31 09:47 UTC
It's a nice feature that if the provided `manifest`, `defaultCR` is possible to fetch directly from URL.

AC:

- [ ] CLI can get `manifest`, `defaultCR` data from remote URL.

**Comment by janmedrek** [comment] 2023-12-15 10:37
Duplicate of: https://github.com/kyma-project/cli/issues/1782

**Closed by janmedrek** 2023-12-15 10:37 UTC
