### ISSUE TITLE
New installation: forced folder deletion 

### ISSUE THREAD

**Issue by colunira** [kyma-project/cli#748] opened 2021-02-08 11:04 UTC
**Description**

Command `kyma alpha deploy` deletes the folder provided by the `--workspace` flag if it exists without asking for permission. 

**Expected result**

CLI asks if I want to remove the data or creates a new folder for Kyma (e.g. workspace/kyma)

**Actual result**

CLI deletes folder provided as a workspace.

**Steps to reproduce**

1. Run `make build-darwin`
2. Run `./bin/kyma-darwin alpha deploy -w ~/Desktop/data/testing -s=master`
    ```
    - No previous Kyma version found
    - Prepare Kyma download
    Error: failed to parse the source flag. It can take one of the following: 'local', 'master', release version (e.g. 1.4.1), commit hash (e.g. 34edf09a) or installer image
    / Downloading Kyma into workspace folder %
    ```
3. Provided folder is deleted.

**Troubleshooting**

**Comment by tobiscr** [comment] 2021-03-12 08:50
This issue was fixed with https://github.com/kyma-project/cli/pull/735. Please let me know if the issue isn't fixed as it would be expected.

**Closed by tobiscr** 2021-03-12 08:50 UTC
Labels: area/cli, area/installation
