### ISSUE TITLE
Failing `kyma-cli-compatibility-2` job

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/cli#921] opened 2021-06-17 07:30 UTC
**Description**

The `kyma-cli-compatibility-2` job started failing on 2021-04-24.
It fails with the following error:
```
Error: Function.serverless.kyma-project.io "first-function" is invalid: 
spec.runtime: Unsupported value: "nodejs14": supported values: "nodejs12", "nodejs10", "python38"
```
One of failing exexutions: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-compatibility-2/1405359601129361408

It looks like it chooses wrong Kyma version (one that doesn't support nodejs14).

**Expected result**

Should be green :)

**Comment by elchead** [comment] 2021-06-18 09:05
@adamwalach it should be fixed now :)

**Comment by elchead** [comment] 2021-06-18 09:37
The job works as expected now. But Kyma CLI is incompatible with 1.22 because of recent update to Node 14. Could you check to provide compatibility for second last version in that serverless function? @pPrecel

**Comment by adamwalach** [comment] 2021-06-22 10:19
This issue is about failing job. I see that it is still red, and it sends alerts every day.
@elchead if you think some other team should provide a fix, please assign them or create a follow-up ticket to track this problem.

**Comment by pPrecel** [comment] 2021-06-22 11:14
The `nodejs10` runtime is removed and the `nodejs14` is an default. I think we can't provide those changes because CLI from the `main` branch should be compatible with the `main` kyma branch and the use of older runtimes should be not permitted. How @elchead said this job works as expected and I think that this job should be disabled OR if you want to get rid of the problem - use `kyma init function` (in the test scenario) with the  `--runtime nodejs12` flag which is a common version for last few kyma releases and will work.

Here is information about CLIs possible compatibility:
https://github.com/kyma-project/cli/blob/main/docs/internal/compatibility-template.md

**Comment by adamwalach** [comment] 2021-06-22 11:27
`compatibility-1` started failing as well - https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-compatibility-1/1407126386824450048 is this expected as well?

If I understood correctly, these "compatibility" pipelines will be red till next Kyma release is out. 
In this case I'd like to remove them and you can bring them back when they are needed.
@elchead, do you agree?

**Comment by elchead** [comment] 2021-06-23 12:31
The issue is fixed now :) @adamwalach 
Now the runtime is set to nodejs12 in the test, as suggested by @pPrecel and Icke.

Prow Jobs:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-compatibility-1/1407673471814602752
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-cli-compatibility-2/1407673550696878080

**Closed by elchead** 2021-06-23 12:31 UTC
Labels: area/ci, bug

**Comment by adamwalach** [comment] 2021-06-23 14:46
Thank you! :)
