### ISSUE TITLE
Install kyma from local sources support for non-minikube clusters

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/cli#331] opened 2019-12-08 21:10 UTC
**Description**
Support the installation of kyma from local sources for remote clusters. For that, the docker image of the kyma-installer needs to be pushed to a remote docker registry (which needs to be provided as input by the user), from there it can be installed in the regular way.

**Reasons**
The non-local setup is the standard case and must be supported for the local source scenario as well.

**Attachments**

**Comment by suleymanakbas91** [comment] 2020-04-29 13:35
Duplicate of https://github.com/kyma-project/cli/issues/334

**Closed by suleymanakbas91** 2020-04-29 13:35 UTC
Labels: area/cli
