### ISSUE TITLE
CLI can't push image to docker hub oci registry

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/cli#1494] opened 2023-01-02 13:02 UTC
[docker support oci already](https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/), however, kyma cli can't push image to oci registry by offering `-c` flag with `username:accesstoken`

```
Error: unable to push config: server message: insufficient_scope: authorization failed
```

_Update: We now know this is caused by the generated oci artifact reference that has more than two path segments, while the dockerhub registry only allows for two. I am extending the AC's for this task_

AC:
- [ ] cli should support docker hub oci registry (edit: this is the original AC)
- [ ] `kyma alpha create module` should allow users to fully control the oci artifact reference (URL) via flags.

### Proposed syntax change:

1. Two parameters for the entire artifact reference: version + registry
syntax: `kyma alpha create module --version 0.0.5 --registry 'registry-1.docker.io/someuser/module' -c 'credentials'`
The resulting ref would be: `registry-1.docker.io/someuser/module:0.0.5`
The `--name` flag would be dropped from the CLI.

2. Two parameters that define the artifact reference: version + registry + name
syntax: `kyma alpha create module --version 0.0.5 --registry 'registry-1.docker.io' --name 'someuser/module' -c 'credentials'`
The resulting ref would be: `registry-1.docker.io/someuser/module:0.0.5`

**Comment by janmedrek** [comment] 2023-01-09 10:29
We would need to investigate whether the OCI images without the docker layer can be pushed to the docker registry at all.

Besides that - we need to clarify what are the requirements regarding docker hub support.

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-10 07:34
@ruanxin I confirm that docker hub should support OCI images. I have made a few tests using [ORAS](https://oras.land/cli/) tool. But I can't reproduce your error. Can you paste your command (without credentials)? Thanks!

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-11 08:44
Thanks, I was able to reproduce it using template operator.
From what I can see, our current code cannot push, but before pushing it tries to `fetch` - which makes sense, because the artifact/layer may already be pushed. And that `fetch` also fails, with a similar error
Here's the relevant entry from the logs (debug mode):
`DEBU[0007] Unable to check existence, continuing with push  error="server message: insufficient_scope: authorization failed"`
The `check existence` refers to the previous `HEAD` calls which are related to the mentioned `fetch` action.

**Comment by ruanxin** [comment] 2023-01-12 09:12
Regarding the registry name length limit which specific to docker hub (if it's the fact), I think we should allow user to provide an alternative name if default generated name is compatible with docker hub definition`module/component-descriptors/kyma-project.io/template-operator`, the registry name is not in the definition of [opencontainer image spec](https://github.com/opencontainers/image-spec).

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-12 09:51
It looks like the source of the problem is that the central docker registry API (registry-1.docker.io) has problems accepting artifact (layers/manifests) names with more than 2 path components in it.
And it doesn't fail nicely, it just rejects API requests with `401 insufficient_scope: authorization failed`

Below I provide the details assuming the following CLI invocation inside a Kubebuilder project directory:
`kyma alpha create module -v --version 0.0.5 -w --registry registry-1.docker.io/someuser/module -c 'credentials'`

In the CLI we're building the `ref` (full artifact name) from three parts:
- repository name - provided by the user in the CLI flag, e.g: `--registry registry-1.docker.io/someuser/module`
- `component-descriptors` - an intermediate path segment, added by gardener's `bindings-go` library used in the CLI
-  the artifact "name" - if not provided explicitly in the flags, assumed from the Kubebuilder project name, e.g.: `kyma-project.io/template-operator`

Then of course the version/tag is appended as provided by the user.
This gives the following artifact reference used in the API calls: `registry-1.docker.io/someuser/module/component-descriptors/kyma-project.io/template-operator:0.0.5`

@ruanxin You are right. I am now verifying if the docker registry accepts the artifact from the CLI if the path is shorter - we may face other issues. If that works, then the shorter name is already there: it's in the `--registry registry-1.docker.io/someuser/module` CLI flag

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-12 14:21
After I forced an artifact reference with only 2 path segments by manually patching the code, the push was successful.
It is stored as type "Other" with proper media type visible: `application/vnd.gardener.cloud.cnudie.component.config.v1+json`
I think we have to change the way the `kyma alpha create module` works in terms of building oci artifact reference.

**Comment by adityabhatia** [comment] 2023-01-12 15:32
Another issue which is related to image naming is giving the user flexibility to choose a name for the module-operator image. The module operator image name currently includes unnecessary elements, especially for third party module developers, like `kyma-project.io` and `component-descriptor`. Maybe this can be solved as part of this ongoing issue concerning image naming. The desired solution should like `<registry>/<user-provided-image-name>@sha256:<digest>`

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-13 08:14
@adityabhatia I've updated the issue with proposed syntax change. Any idea on how could we introduce the `@sha256:<digest>` syntax into the existing CLI flags? Feel free to provide another option for the proposed syntax change. Thanks!

**Comment by pbochynski** [comment] 2023-01-13 13:40
We already got the feedback that users want to have full control over the image name and path (without generated path segments like `component-descriptors/kyma-project.io`)
One comment about the name flag - it is also not clear what is the name you provide. Is it the module name that is used as a module template label (`operator.kyma-project.io/module-name`) or is it the component descriptor name? The second is with the prefix that is somehow mandatory (even if you don't use kubebuilder). 
In general, I prefer explicit configuration and full control of all names with CLI flags. If not provided you can fallback to defaults derived from kubebuilder project structure.

**Comment by clebs** [comment] 2023-01-16 08:52
I agree with the general approach of the user having as much control as possible, but we also need to consider the limitations. 
We need to comply with the OCI spec, the OCM spec for the component descriptor and additionally Docker Hub.

These restrictions might contradict each other and so we need to find a way to do 2 things:
1. Allow full control for module names and registry URLs and paths; ideally without adding any more flags(make them smart).
2. Revisit how name validation is done to guarantee that all cases are covered always and guarantee a successful component descriptor creation and push.

I would also avoid fallbacks and defaults that magically apply if the name + registry combination provided is not complete. Descriptive feedback allows the user to decide.

@Tomasz-Smelcerz-SAP, to have a good design here, I suggest making an exhaustive analysis of name + registry patterns, identify all compliant ones and all possible wrong ones and create a testing matrix out of it.
With that matrix, proper validation and error feedback can be defined for each row/column and then be implemented with confidence.

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-23 08:22
@pbochynski update for your concerns:
- `We already got the feedback that users want to have full control over the image name and path`: I am afraid this is impossible, due to the OCM libraries we're using. See the linked [PR](https://github.com/kyma-project/cli/pull/1502) for details.
We essentially have four options here:
  1. Change the OCM spec somehow
  2. Change the Dockerhub limitations somehow
  3. Switch from OCM to something else. Perhaps just plain vanilla artifact, like [ORAS](https://oras.land/)?
  4. Use OCM libraries in a "crippled" mode, against the spec - forcing the paths as we like. It may require a fork of the libraries.

- `One comment about the name flag - it is also not clear what is the name you provide`:  This is not the module template name, this is the Component Name as defined by the [OCM spec](https://gardener.github.io/component-spec/component_descriptor_registries.html#component-name-mapping). It must be something like: `kyma.io/somename`. This will be part of the OCI artifact URL that must contain this ugly `/component-descriptors/` path segment - in default mapping mode. My [PR](https://github.com/kyma-project/cli/pull/1502) provides a working (although also ugly) alternative.

**Closed** 2023-01-30 12:49 UTC
Labels: kind/bug

**Comment by Tomasz-Smelcerz-SAP** [comment] 2023-01-31 08:20
## Summary ##
We're not able to fulfill all the ACs here. Mainly we're not free to chose arbitrary artifact URLs, we're constrained by the OCM spec. Dockerhub support comes with a price - we have to use the `sha256-digest` name mapping. It leads to an artifact URL that is not human-readable, it contains a sha256 of the original artifact name.
See #1502 for details.
