### ISSUE TITLE
MacOS 10.15.7 - kyma console won't start after restart or reboot

### ISSUE THREAD

**Issue by sundarvc** [kyma-project/cli#617] opened 2020-10-15 12:07 UTC
Hi all,

minikube 1.14.0
kubernetes client/server 1.18.8/1.16.3 
Kyma CLI version: 1.15.1
driver = hyperkit

Everything works fine after running , kyma provision minikube --vm-driver=hyperkit , first time.

However after restart of laptop , running kyma console gives following error:

**Reading the Kyma console URL from the cluster
Unable to read the Kyma console URL due to error: the server could not find the requested resource (get virtualservices.networking.istio.io console-web). Check if your cluster is available and has Kyma installed**

Because of this I am having to run minikube delete, then reinstall the driver , and do kyma install after reboot.

Any suggestions ?

Thanks,
Sundar

**Comment by a-thaler** [comment] 2020-10-15 12:45
Please check if kyma is installed at all after restart. We face a really bad situation that after restart the cluster gets resetted.
See also https://github.com/kyma-project/cli/issues/455

We still have no idea how to fix it, in meantime we are working on a solution based on k3s: https://github.com/kyma-incubator/local-kyma-k3d

**Comment by sundarvc** [comment] 2020-10-15 13:31
Thanks for your help.

After restart , kyma version gives following error.

> kyma version
Kyma CLI version: 1.15.1
Unable to get Kyma cluster version due to error: Get "https://192.168.64.10:8443/api/v1/namespaces/kyma-installer/pods?labelSelector=name%3Dkyma-installer": context deadline exceeded (Client.Timeout exceeded while awaiting headers). Check if your cluster is available and has Kyma installed

**Comment by a-thaler** [comment] 2020-10-15 19:06
yes, I see. Have you checked if kyma is installed as the message indicates?
Just call "kubectl get namespaces" and check if there is a "kyma-system" namespace. I suspect that it is gone. See the linked ticket for more details

**Comment by sundarvc** [comment] 2020-10-15 21:15
After restart,
> kubectl get namespaces
The above command hangs with no output.
>kubectl get ns 
This one also hangs the same way.

If I then do the following, then I get these responses:

> minikube start

😄  minikube v1.14.0 on Darwin 10.15.7
🆕  Kubernetes 1.19.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.2
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
🐳  Preparing Kubernetes v1.16.3 on Docker 19.03.12 ...
🤦  Unable to restart cluster, will reset it: addons: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.3:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:

stderr:
error execution phase addon/coredns: unable to patch the CoreDNS deployment: Internal error occurred: failed calling webhook "legacysinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/legacysinkbindings?timeout=10s: dial tcp 10.99.6.98:443: i/o timeout
To see the stack trace of this error execute with --v=5 or higher


🔎  Verifying Kubernetes components...
🌟  Enabled addons: metrics-server, storage-provisioner, default-storageclass

❗  /usr/local/bin/kubectl is version 1.18.8, which may have incompatibilites with Kubernetes 1.16.3.
💡  Want kubectl v1.16.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" by default

>kubectl get namespaces

NAME              STATUS   AGE
default           Active   13s
kube-node-lease   Active   14s
kube-public       Active   14s
kube-system       Active   14s

**Comment by a-thaler** [comment] 2020-10-22 12:44
So in the namespaces list you can see that there is no kyma installation anymore, that's why there is no kyma console anymore.
Will close the ticket as a duplicate of #455

**Closed by a-thaler** 2020-10-22 12:44 UTC
Labels: area/cli, bug
