### ISSUE TITLE
CLI does not allow passing custom certificates for the default domain

### ISSUE THREAD

**Issue by peteral** [kyma-project/cli#681] opened 2020-12-21 10:15 UTC
**Description**

Attempted to install a local kyma-cluster with custom domain and certificate on minikube in Ubuntu 20.10.

`kyma install --domain $DOMAIN --tls-key $TLS_KEY --tls-cert $TLS_CERT -c components.yaml`

![kyma-install-error](https://user-images.githubusercontent.com/6490406/102765819-6fc3ad80-437d-11eb-9d74-41e30141fe0e.png)

$DOMAIN = kyma.local

**Expected result**

Working installation.

**Actual result**

`Error: You specified one of the --domain, --tls-key, or --tls-cert without specifying the others. They must be specified together`

Assumption - the parameters '--tls-key' and '--tls-cert' have been renamed in 1.18.0, maybe the check was not updated?

**Steps to reproduce**

See screenshot.

**Comment by suleymanakbas91** [comment] 2020-12-21 13:18
That's strange.. I tried it on Mac and on Ubuntu 20.04, with and without using environment variables, but I couldn't reproduce this. 

I see that renaming change didn't touch the validation logic, but only changed the error message. So, I doubt this is related to that change. 

@peteral this is reproducible on your side, right?

**Comment by peteral** [comment] 2020-12-22 08:21
@suleymanakbas91 

Yes, I can reproduce it. Tried without the components file with the same result. Simplest explanation would be a typo, but I checked at least ten times and don't see it.

I'll check out kyma and try it in debugger and then let you know.

**Comment by peteral** [comment] 2020-12-22 08:50
Ok, I know what happened. The problem is that I am trying to use my own certificate for the default domain, which is for some reason forbidden in the check:
![image](https://user-images.githubusercontent.com/6490406/102868592-a7445f80-443a-11eb-9583-fd993793d303.png)

The reason I am doing is that I am unable to import the auto-generated certificate into Firefox so I am creating my own certificate which might not be 100% correct, but contains all the info Firefox requires to accept the certificate.

Before I was using kyma on microk8s with xip.io. But this does not work any more since 1.17.0 because the installation won't finish. So I moved to minikube and though kyma.local is a nice enough domain name to use.

I can work around this by using a different domain name.

**Comment by suleymanakbas91** [comment] 2021-01-05 13:41
Thanks for the detailed information @peteral! I've adapted the title of the bug.

**Comment by tobiscr** [comment] 2021-01-15 11:00
We are currently replacing the old installation mechanism (planned rollout is Q1/2021) and the new approach will support this option.

https://github.com/kyma-project/cli/blob/master/cmd/kyma/alpha/deploy/opts.go#L95

In the meantime, we will add this option also the old installation approach (#696 ).

**Comment by peteral** [comment] 2021-01-16 08:44
Cool, thanks for the quick fix

**Comment by tobiscr** [comment] 2021-01-19 13:49
Thanks for the positive feedback! 👍 Will close this ticket.

**Closed by tobiscr** 2021-01-19 13:49 UTC
Labels: area/cli, bug
