### ISSUE TITLE
Prompt to remove existing minikube cluster even after minikube delete

### ISSUE THREAD

**Issue by johnkbarrow** [kyma-project/cli#149] opened 2019-06-28 10:21 UTC
**Description**
After "minikube stop" and "minikube delete", "kyma provision minikube" prompts to remove existing Minikube cluster. Answering y leads to an error from "minikube delete". Rerunning "kyma provision minikube" successfully launches minikube as expected.

**Expected result**

Minikube is provisioned
**Actual result**

Error from "minikube delete"
**Steps to reproduce**

See attached screenshot showing the whole flow.
**Troubleshooting**

Rerun "kyma provision minikube"
![Screenshot 2019-06-28 at 11 26 14](https://user-images.githubusercontent.com/47791539/60336190-8f039980-9997-11e9-82b9-4c8a8465fbb8.png)

**Comment by hisarbalik** [comment] 2019-06-28 12:03
can you let know the version of CLI you using (from command -> kyma version)

**Comment by johnkbarrow** [comment] 2019-06-28 12:06
Kyma CLI version: 1.2.0

**Comment by johnkbarrow** [comment] 2019-06-29 13:53
This might be a timing issue - the error appears whenever i try to provision minikube immediately after deleting it. If there is a delay between deleting and then trying to provision, I don't see the error.

**Comment by johnkbarrow** [comment] 2019-07-08 17:58
Ignore last comment, just received the error even though I deleted the previous cluster 3 days ago.

**Comment by suleymanakbas91** [comment] 2019-09-02 13:21
This could be related to the minikube version. I couldn't reproduce it using the recommended version `1.0.1`. I'm closing the issue, but feel free to reopen if you hit it again using the recommended version.

**Closed by suleymanakbas91** 2019-09-02 13:21 UTC
Labels: area/cli, bug
