### ISSUE TITLE
coredns pod fails to start after restarting minikube

### ISSUE THREAD

**Issue by dongyingbo** [kyma-project/cli#1206] opened 2022-03-09 04:21 UTC
**Description**

Restart minikube and you see coredns pods fails to start.

**Expected result**

The cluster should be in health after restarting minikube

**Actual result**

You see coredns fails to start
```
kube-system        coredns-558bd4d5db-2lzwv                                          0/1     CrashLoopBackOff   2          5m55s

```

**Steps to reproduce**

1. Start minikube via `minikube start --kubernetes-version="1.21.7"`
2. Install Kyma via `kyma deploy`
3. Restart minikube

**Troubleshooting**

Logs of coredns,
```
[WARNING] plugin/hosts: File does not exist: /etc/coredns/NodeHosts
plugin/hosts: this plugin can only be used once per Server Block
```
Content of coredns configmap,
```
        ...
        hosts /etc/coredns/NodeHosts {
          reload 1s
          fallthrough
        }
        ...
        hosts {
           192.168.49.1 host.minikube.internal
           fallthrough
        }
        ...

```

**Comment by a-thaler** [comment] 2022-03-09 08:34
@dongyingbo as we had too much problems with minikube, with kyma 2.x we switched to K3D as the supported local environment. The "kyma provision minikube" command is deprecated and is tested only with a kyma 1.x version.
Do you encountered problems with K3D or you have not tried it out yet?

**Comment by dongyingbo** [comment] 2022-03-09 08:53
@a-thaler 
I tried `kyma provision k3d; kyma deploy` and run into "pod not scheduled" issue because of insufficient resources.
Perhaps I need to open another issue for that - in document we need to say check KUBECONFIG environment between provision k3d and deploy as it does not switch context of kube configration automatically.

**Comment by dongyingbo** [comment] 2022-03-09 09:13
I did not use "kyma provision minikube". I just run `minikube start --kubernetes-version="1.21.7"`.
I just checked my kyma cli (version 2.0.4) and it said "minikube    [DEPRECATED] Provisions Minikube." In my opinion "deprecated" means it should work still.

**Comment by a-thaler** [comment] 2022-03-24 15:30
Hi @dongyingbo,
- about the insufficient resources you are right, I created a docu bug to follow up on that: https://github.com/kyma-project/kyma/issues/13723
- the KUBECONFIG env variable problem I'm not aware of, that worked always seemless for me. After the "kyma provision k3d" call, the kubeconfig file where my KUBECONFIG points to gets the new config merged into and set as default, so that the next call will use it. Can you please provide more details on the problem
- The minikube setup always required special settings, that's why we introduced the "kyma provision minikube" command initially. Still we had serious problems with the minikube solution like the problem which you reported. The solution was the switch to K3D. We kept the old minikube command for now as Kyma1 installations will not work on K3D. We will remove it together with the deprecated "kyma install" command (for kyma1 installations)  probably with 2.2

**Comment by tobiscr** [comment] 2022-06-09 06:39
Hi @dongyingbo , is the provided solution acceptable for you? We recommend to use k3d for local testing, alternatively you can setup a K8s on a hyperscaler. 

If the issue is not solved for you, please let me know. Otherwise I would close the issue in the coming days.

**Closed** 2022-08-11 08:14 UTC
Labels: question, area/cli
